---
- name: restart jellyfin
  systemd:
    name: jellyfin
    state: restarted
  become: yes

- name: restart nginx
  systemd:
    name: nginx
    state: restarted
  become: yes

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  become: yes